---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-storage-pv-claim
  namespace: quay-enterprise
  labels:
    app: quay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
